apiVersion: v1
kind: Pod
metadata:
  name: secret-demo-1
spec:
  containers:
  - name: demo-container
    image: nginx
    env:
    - name: username
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: username
    - name: password
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: password