apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo-1
spec:
  securityContext: # security context in pod level
    runAsUser: 1000
    runAsGroup: 2000
    fsGroup: 3000
  volumes:
  - name: demo-vol
    emptyDir: {}
  containers:
  - name: sc-demo-1
    image: busybox:1.28
    command: ["sh","-c","sleep 1h"]
    volumeMounts:
    - name: demo-vol
      mountPath: /data/demo