apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-secret
  namespace: development # for specific ns
subjects:
- kind: User  # user/group/service account --> you can define 
  name: dev
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: secret-reader # name of cluster-role
  apiGroup: rbac.authorization.k8s.io