apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo-3
spec:
  containers:
  - name: sc-demo-3
    image: ubuntu
    command: ["sh","-c","sleep 1h"]
    securityContext: # provide capabilites 
      capabilities:
        add: ["NET_ADMIN"]